### ISSUE TITLE
Plotting functions.

### ISSUE THREAD

**Issue by franciscomalveiro** [vsubbian/WindowSHAP#1]
Hello!
First of all, thanks for the development of this tool, which I've been using it to generate explanations for the predictions of an LSTM model. By following the [original paper](https://arxiv.org/abs/2211.06507), I've noticed there are some nice plots displayed, however in the [pip package](https://pypi.org/project/windowshap/#files) I cannot find the code that plots them.

By browsing through this repository and the provided notebook, I believe I've found functions on the [util](https://github.com/vsubbian/WindowSHAP/blob/8d296d06530878de8d10f3a2851d51239b4c1940/util.py) module which perform the plotting. For that reason, would it be possible to make these functions publicly available on the mentioned package?

Thanks!

**Comment by aminnayebi** [comment]
Hi,

Thank you for your interest in our method. I am sorry for a late reply. I am working on making the plots available as a method of the explanation classes so that it would be easier to use them. However, until then, you can use the `heatmap()` function in the `util.py` file to plot the time series alongside their explanations.

**Comment by franciscomalveiro** [comment]
Will do then, thanks!
